name: DevSecOps

on:
  workflow_dispatch

jobs:
  devsecops:
    name: DevSecOps
    uses: io-workflows/io-workflows/.github/workflows/devsecops.yml@main
    with:
      project-language: 'C++'
      verbose-option: 'SilentlyContinue'
    secrets: inherit
